# Generated by Django 5.0.4 on 2024-04-27 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MiniProjectsModal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('keywords', models.JSONField()),
                ('link', models.URLField()),
                ('image_name', models.CharField(max_length=100)),
            ],
        ),
    ]
