# Generated by Django 5.0.2 on 2024-04-07 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectsModal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('href', models.URLField(blank=True, null=True)),
                ('links', models.JSONField(default=list)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
